"""
CLI entry point for the decay heat preprocessor.

Reads an isotope inventory CSV, runs the full Bateman decay chain solver,
fits a sum-of-exponentials to the output, and prints the fitted parameters
formatted for direct paste into ``solver_config.yaml``.

Usage::

    decay-preprocessor \\
        --inventory path/to/inventory.csv \\
        --chain     path/to/chain.xml \\
        --output-dir  results/decay

Heat output is normalised to W/kg using a mass derived from the inventory's own
atom counts, so no mass need be supplied.  ``--sample-mass`` overrides it, for
the case where the CSV deliberately lists only part of the waste.

The size of the waste *campaign* is a separate matter entirely and is not
handled here — specific power does not depend on how much waste there is.  Set
``campaign.total_waste_mass_kg`` in ``solver_config.yaml`` instead.

The inventory CSV must have two columns:

- ``Isotope`` — nuclide name string matching the chain file (e.g. ``"Co60"``)
- ``Atoms``   — number of atoms at t = 0

Chain XML files (OpenMC format) can be obtained from:
    https://openmc.org/nuclear-data/

Output files written to ``--output-dir`` (default: current directory):

- ``waste_source.yaml`` — fitted decay terms + masses; reference this from
  ``solver_config.yaml`` via ``waste_source:``
- ``decay_curve.csv`` — raw Bateman solution (Time_Years, Heat_Watts, Specific_Power_W_kg)
- ``decay_fit.png``   — diagnostic plot comparing Bateman solution to fitted curve
"""

import argparse
import sys
from pathlib import Path

import pandas as pd
import yaml

from decay_preprocessor.chain_parser import parse_chain
from decay_preprocessor.bateman_solver import solve_decay
from decay_preprocessor.decay_fitter import fit_decay_curve, plot_fit
from decay_preprocessor.inventory import inventory_mass_kg


def write_waste_source(
    path,
    terms,
    sample_mass_kg,
    r2,
    rmse,
    inventory=None,
    chain=None,
):
    """
    Write the fitted waste stream to a standalone ``waste_source.yaml``.

    This is the handoff between the two halves of the toolchain.  A separate
    file is used rather than editing ``solver_config.yaml`` in place: the
    config is hand-written and full of comments, and rewriting it by line
    matching is fragile — it silently depends on indentation and on being run
    from the right working directory.  A generated file is also the honest
    representation, since everything in it is derived output that should be
    regenerated rather than hand-edited.

    Point the solver at it with ``waste_source: path/to/waste_source.yaml``.

    Parameters
    ----------
    path : Path
        Destination file.
    terms : list of (float, float)
        Fitted ``(Amplitude [W/kg], DecayConstant [1/yr])`` pairs.
    sample_mass_kg : float
        Mass the decay curve is normalised by — recorded as provenance, since
        every value in ``decay_terms`` scales with it.
    r2, rmse : float
        Fit quality, recorded so a stale or poor fit is visible downstream.
    inventory, chain : str, optional
        Source paths, recorded for provenance.
    """
    payload = {
        "decay_terms": [[float(f"{A:.6g}"), float(f"{lam:.6g}")] for A, lam in terms],
        "sample_mass_kg": float(sample_mass_kg),
        "fit_r_squared": float(r2),
        "fit_rmse_W_per_kg": float(rmse),
    }
    if inventory is not None:
        payload["source_inventory"] = str(inventory)
    if chain is not None:
        payload["source_chain"] = str(chain)

    header = (
        "# Generated by the AETHON decay preprocessor - do not edit by hand.\n"
        "# Regenerate with: decay-preprocessor --inventory ... --chain ...\n"
        "#\n"
        "# Reference from solver_config.yaml with:\n"
        f"#   waste_source: {Path(path).name}\n\n"
    )
    # default_flow_style=None keeps the outer mapping in block style while
    # rendering each [amplitude, lambda] pair inline, matching how decay_terms
    # are written by hand in solver_config.yaml.
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=None)
    Path(path).write_text(header + body, encoding="utf-8")


# A supplied mass this far from the computed one is more likely a mistake than
# a genuinely partial inventory. Confusing waste mass with canister mass is off
# by roughly the inverse loading fraction, so an order of magnitude.
_MASS_DISCREPANCY_FACTOR = 2.0


def _resolve_sample_mass(supplied, computed):
    """
    Decide which mass to normalise by, and say so.

    The computed value comes from the inventory's own atom counts and is right
    whenever the CSV lists every nuclide present. An override is legitimate for
    a partial inventory, but is also how a mistake enters, so a large
    disagreement is worth flagging rather than accepting in silence.

    Parameters
    ----------
    supplied : float or None
        The ``--sample-mass`` override, if given.
    computed : float
        Mass derived from the inventory [kg].

    Returns
    -------
    float
        The mass to use [kg].
    """
    if supplied is None:
        return computed

    print(f"      Using --sample-mass override; inventory implies "
          f"{computed:.6g} kg")

    if computed > 0.0:
        ratio = supplied / computed
        if ratio > _MASS_DISCREPANCY_FACTOR or ratio < 1.0 / _MASS_DISCREPANCY_FACTOR:
            print(
                f"      Warning: that is {ratio:.3g}x the inventory mass.\n"
                "      Expected if the inventory is deliberately partial. If "
                "not, check you have\n"
                "      not supplied a canister or glass-composite mass - "
                "specific power must be\n"
                "      per kg of waste, and every temperature scales with it.",
                file=sys.stderr,
            )

    return supplied


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Decay Heat Preprocessor - Bateman solver + exponential fitter",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )

    # --- Required arguments --------------------------------------------------
    parser.add_argument(
        "--inventory", required=True,
        help=(
            "Path to isotope inventory CSV (columns: Isotope, Atoms). "
            "Lines starting with '#' are treated as comments."
        ),
    )
    parser.add_argument(
        "--chain", required=True,
        help=(
            "Path to OpenMC-format decay chain XML file. "
            "Chain files can be obtained from https://openmc.org/nuclear-data/"
        ),
    )
    # --- Optional arguments --------------------------------------------------
    parser.add_argument(
        "--sample-mass", type=float, default=None,
        help=(
            "Override the waste mass [kg]. By default it is computed from the "
            "inventory's own atom counts, which is correct whenever the CSV "
            "lists every nuclide present. Supply this only if your inventory "
            "is partial - radioactive species only, say - and you know the "
            "true mass."
        ),
    )
    parser.add_argument(
        "--duration", type=float, default=50.0,
        help=(
            "Simulation duration [years] (default: 50.0). The fit is only "
            "trustworthy inside this range, so it should cover the longest "
            "time the solver will be asked about."
        ),
    )
    parser.add_argument(
        "--output-dir", default=".",
        help="Directory for output files (default: current directory).",
    )
    parser.add_argument(
        "--n-points", type=int, default=2000,
        help="Number of log-spaced time evaluation points (default: 2000).",
    )
    parser.add_argument(
        "--cutoff-years", type=float, default=1 / 12,
        help=(
            "Exclude data before this time [yr] when fitting (default: 1/12, about 1 month). "
            "Discards short-lived nuclides irrelevant to long-term cooling."
        ),
    )
    parser.add_argument(
        "--no-waste-source", action="store_true",
        help=(
            "Skip writing waste_source.yaml and print the fitted terms only."
        ),
    )

    args = parser.parse_args(argv)

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # --- Step 1: Parse chain file --------------------------------------------
    print(f"[1/4] Parsing chain file:  {args.chain}")
    nuc_to_idx, decay_constants, q_values, matrix_A = parse_chain(args.chain)
    print(f"      {len(nuc_to_idx):,} nuclides loaded.")

    # --- Step 2: Load inventory ----------------------------------------------
    print(f"[2/4] Loading inventory:   {args.inventory}")
    inventory_df = pd.read_csv(args.inventory, comment="#")
    n_matched = sum(1 for iso in inventory_df["Isotope"] if iso in nuc_to_idx)
    print(
        f"      {len(inventory_df)} isotopes in inventory, "
        f"{n_matched} matched to chain."
    )
    if n_matched == 0:
        print(
            "ERROR: No inventory isotopes matched the chain file. "
            "Check nuclide naming conventions.",
            file=sys.stderr,
        )
        return 1

    computed_mass, unparsed = inventory_mass_kg(inventory_df)
    if unparsed:
        print(
            f"      Warning: no mass number in {len(unparsed)} name(s), "
            f"contributing no mass: {', '.join(unparsed[:5])}"
            + (" ..." if len(unparsed) > 5 else ""),
            file=sys.stderr,
        )

    sample_mass = _resolve_sample_mass(args.sample_mass, computed_mass)
    print(f"      Waste mass: {sample_mass:.6g} kg")

    # --- Step 3: Solve Bateman equations -------------------------------------
    print(f"[3/4] Solving decay chain for {args.duration:.1f} years ...")
    result_df = solve_decay(
        inventory_df=inventory_df,
        nuc_to_idx=nuc_to_idx,
        decay_constants=decay_constants,
        q_values=q_values,
        matrix_A=matrix_A,
        sample_mass_kg=sample_mass,
        duration_years=args.duration,
        n_points=args.n_points,
    )
    csv_path = output_dir / "decay_curve.csv"
    result_df.to_csv(csv_path, index=False)
    print(f"      Saved: {csv_path}")

    # --- Step 4: Fit sum-of-exponentials -------------------------------------
    print("[4/4] Fitting sum-of-exponentials ...")
    terms, r2, rmse = fit_decay_curve(
        result_df["Time_Years"].values,
        result_df["Specific_Power_W_kg"].values,
        cutoff_years=args.cutoff_years,
    )

    # --- Print YAML-ready output ---------------------------------------------
    print("\n" + "=" * 60)
    print(f"Fit quality:  R^2 = {r2:.8f}  |  RMSE = {rmse:.2f} W/kg")
    print(f"Terms fitted: {len(terms)}")
    print("=" * 60)
    print("\ndecay_terms (W/kg, 1/yr):\n")
    for A, lam in terms:
        print(f"    - [{A:.6g}, {lam:.6g}]")
    print()

    # --- Save diagnostic plot ------------------------------------------------
    plot_path = output_dir / "decay_fit.png"
    plot_fit(
        result_df["Time_Years"].values,
        result_df["Specific_Power_W_kg"].values,
        terms,
        r2,
        output_path=plot_path,
    )
    print(f"Plot saved:   {plot_path}")

    # --- Write the handoff file ---------------------------------------------
    if not args.no_waste_source:
        source_path = output_dir / "waste_source.yaml"
        write_waste_source(
            path=source_path,
            terms=terms,
            sample_mass_kg=sample_mass,
            r2=r2,
            rmse=rmse,
            inventory=args.inventory,
            chain=args.chain,
        )
        print(f"Waste source: {source_path}")
        print(
            f"\nAdd to solver_config.yaml:\n"
            f"    waste_source: {source_path}"
        )

    print("\nDone.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
